[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking = "ANcqthEwGEQwKh7JoPLTsbW3atyf1civUBnQ22iTgRH1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/whanod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
