[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking = "ATfdE39GhVCzGEeX8kVnbPwb1Uur7fBX8jCU1SrL3Swq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/whanod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metaplex_token_metadata_program.so"

[[test.genesis]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
program = "auth.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[workspace]
types = "app/src/idl/"

[[test.validator.account]]
address = "AXGujE6T556PjoN8yXpN74hQj8uB9B9YDNyCcryLeizW"
filename = "rules.json"